export const wilayat = [
  { english: "Adrar", arabic: "أدرار" },
  { english: "Chlef", arabic: "الشلف" },
  { english: "Laghouat", arabic: "الأغواط" },
  { english: "Oum El Bouaghi", arabic: "أم البواقي" },
  { english: "Batna", arabic: "باتنة" },
  { english: "Béjaïa", arabic: "بجاية" },
  { english: "Biskra", arabic: "بسكرة" },
  { english: "Béchar", arabic: "بشار" },
  { english: "Blida", arabic: "البليدة" },
  { english: "Bouira", arabic: "البويرة" },
  { english: "Tamanrasset", arabic: "تمنراست" },
  { english: "Tébessa", arabic: "تبسة" },
  { english: "Tlemcen", arabic: "تلمسان" },
  { english: "Tiaret", arabic: "تيارت" },
  { english: "Tizi Ouzou", arabic: "تيزي وزو" },
  { english: "Alger", arabic: "الجزائر" },
  { english: "Djelfa", arabic: "الجلفة" },
  { english: "Jijel", arabic: "جيجل" },
  { english: "Sétif", arabic: "سطيف" },
  { english: "Saïda", arabic: "سعيدة" },
  { english: "Skikda", arabic: "سكيكدة" },
  { english: "Sidi Bel Abbès", arabic: "سيدي بلعباس" },
  { english: "Annaba", arabic: "عنابة" },
  { english: "Guelma", arabic: "قالمة" },
  { english: "Constantine", arabic: "قسنطينة" },
  { english: "Médéa", arabic: "المدية" },
  { english: "Mostaganem", arabic: "مستغانم" },
  { english: "M'Sila", arabic: "المسيلة" },
  { english: "Mascara", arabic: "معسكر" },
  { english: "Ouargla", arabic: "ورقلة" },
  { english: "Oran", arabic: "وهران" },
  { english: "El Bayadh", arabic: "البيض" },
  { english: "Illizi", arabic: "اليزي" },
  { english: "Bordj Bou Arréridj", arabic: "برج بوعريريج" },
  { english: "Boumerdès", arabic: "بومرداس" },
  { english: "El Tarf", arabic: "الطارف" },
  { english: "Tindouf", arabic: "تندوف" },
  { english: "Tissemsilt", arabic: "تسمسيلت" },
  { english: "El Oued", arabic: "الوادي" },
  { english: "Khenchela", arabic: "خنشلة" },
  { english: "Souk Ahras", arabic: "سوق أهراس" },
  { english: "Tipaza", arabic: "تيبازة" },
  { english: "Mila", arabic: "ميلة" },
  { english: "Aïn Defla", arabic: "عين الدفلى" },
  { english: "Naama", arabic: "النعامة" },
  { english: "Aïn Témouchent", arabic: "عين تموشنت" },
  { english: "Ghardaïa", arabic: "غرداية" },
  { english: "Relizane", arabic: "غليزان" },
  { english: "El M'Ghair", arabic: "المغير" },
  { english: "El Menia", arabic: "المنيعة" },
  { english: "Ouled Djellal", arabic: "أولاد جلال" },
  { english: "Bordj Badji Mokhtar", arabic: "برج بادجي مختار" },
  { english: "Beni Abbes", arabic: "بني عباس" },
  { english: "Timimoun", arabic: "تميمون" },
  { english: "Touggourt", arabic: "تقرت" },
  { english: "Djanet", arabic: "جانت" },
];
